export default {
  login: "john-smilga",
  id: 42133389,
  node_id: "MDQ6VXNlcjQyMTMzMzg5",
  avatar_url: "https://avatars.githubusercontent.com/u/43405791?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/khanempire",
  html_url: "https://github.com/khanempire",
  followers_url: "https://api.github.com/users/khanempire/followers",
  following_url:
    "https://api.github.com/users/khanempire/following{/other_user}",
  gists_url: "https://api.github.com/users/khanempire/gists{/gist_id}",
  starred_url: "https://api.github.com/users/khanempire/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/khanempire/subscriptions",
  organizations_url: "https://api.github.com/users/khanempire/orgs",
  repos_url: "https://api.github.com/users/khanempire/repos",
  events_url: "https://api.github.com/users/khanempire/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/khanempire/received_events",
  type: "User",
  site_admin: false,
  name: "Md Aamir Khan",
  company: "CodeTheWorld",
  blog: "www.aamirkhan.com",
  location: "Bihar Sharif, Bihar",
  email: "mdaamirkhan7186@gmail.com",
  hireable: null,
  bio: "Creator of CodeTheWorld",
  twitter_username: "khanempire",
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: "2018-08-06T06:48:23Z",
  updated_at: "2020-07-08T05:01:32Z",
};
